### ISSUE TITLE
Unpredictable results with {{KEYDOWN}} and Sticky Super Macro

### ISSUE THREAD

**Issue by Jaid** [BarRaider/streamdeck-supermacro#22]
I am using following macro code in a Sticky Super Macro:

```handlebars
{{KeyDowna}}
{{pause10}}
{{KeyUpa}}
{{pause100}}
{{KeyDownd}}
{{pause10}}
{{KeyUpd}}
{{pause100}}
```

It switches between `a` and `d` every 100 ms, but also ensures that the keys are pressed for at least 10 ms to prevent the game from missing the input.

However, after stopping the Sticky Super Macro, in some cases one `KeyUp` is not executed and therefore a key is pressed for an infinite time. It seems like the stopping the Sticky Super Macro does instantly stop the loop which makes the execution unpredictable. It would be nice if I could choose to always finish the current macro iteration after stopping the Sticky Super Macro, so all `KeyUp`s are properly triggered and the keyboard state after stopping Sticky Super Macro is the same as before execution.

Thank you for that great software! :)

**Comment by BarRaider** [comment]
[Solved in previous version but issue was not closed]

**Comment by Jaid** [comment]
Tested it in v1.6, still reproducible for me. I can take a video to show what problem I mean if you want.

**Comment by BarRaider** [comment]
Please do so I can reopen the issue

**Comment by Jaid** [comment]
https://www.youtube.com/watch?v=owC29lgRwbE

**Comment by BarRaider** [comment]
Thanks for the video, figured out why it was not reproducing for me. Will add a fix for this.

**Comment by BarRaider** [comment]
New `Let macro complete on stop` option available for Sticky SuperMacro. You can wait for the official release or get the latest version in the #beta channel on my discord server. http://discord.barraider.com
